# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.103.0"

default_platform :ios

platform :ios do
  before_all do
    xcode_version = ENV["XCODE_VERSION"] || "10.2.1"
    ensure_xcode_version(version: xcode_version)
  end

  desc "run tests"
  lane :test do |options|
    scan(
      workspace: "VimeoNetworking.xcworkspace",
      scheme: "VimeoNetworking-iOS",
      configuration: "Debug",
      buildlog_path: ".",
      derived_data_path: "build/",
      formatter: 'xcpretty-json-formatter',
      code_coverage: true
    )

    pretty_junit(file_pattern: "fastlane/test_output/report.junit")

    # Fork PRs cannot use danger because CircleCI (rightly) doesn't expose sensitive environment vars which danger makes use of to comment on PRs.
    # So we opt out of danger for fork PRs by checking the `CIRCLE_BRANCH` environment var and matching it against pull/XXXX where XXXX == numeric chars    
    is_fork_pr = (ENV["CIRCLE_BRANCH"] =~ /pull\/[0-9]+/) != nil
    if is_ci? && !is_fork_pr
      danger(use_bundle_exec: false)
    else 
      UI.message "Skipping danger: is_ci? #{is_ci?}, is_fork_pr? #{is_fork_pr}"
    end
  end

  desc "bumps the project and podspec version"
  lane :version_bump do |options|    

    bump_type = options[:bump_type]
    version_number = options[:version_number]
    if bump_type.nil? && version_number.nil?
      UI.user_error!("version_bump requires you to provide a bump_type [patch|minor|major] or specific version_number. Please try again.") 
    end

    increment_version_number(
      bump_type: bump_type,
      version_number: version_number,
      xcodeproj: "VimeoNetworking.xcodeproj"
    )

    version_bump_podspec(
      bump_type: bump_type,
      version_number: version_number
    )
  end


  after_all do |lane|
    
  end

  error do |lane, exception|
    
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
